[aws]
disabled = false
expiration_symbol = "X"
force_display = false
format = "[on](dimmed) [$symbol($profile )(\\($region\\) )(\\[$duration\\] )]($style)"
style = "bold yellow"
symbol = "â˜ï¸  "

[azure]
disabled = true
format = "[on](dimmed) [$symbol($subscription)]($style) "
style = "blue bold"
symbol = "ï´ƒ "

[battery]
charging_symbol = "ó°‚‡ "
disabled = false
discharging_symbol = "ó±ŸŸ "
empty_symbol = "ó°‚ "
format = "[$symbol][$percentage]($style) "
full_symbol = "ó°¹ "
unknown_symbol = "ó°‚‘ "

  [[battery.display]]
  style = "red bold"
  threshold = 20

[buf]
detect_files = [ "buf.yaml", "buf.gen.yaml", "buf.work.yaml" ]
disabled = false
format = "[with](dimmed) [$symbol($version)]($style)"
style = "bold blue"
symbol = "ğŸƒ "
version_format = "v${raw}"

[bun]
detect_files = [ "bun.lockb", "bunfig.toml" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "bold red"
symbol = "ğŸ "
version_format = "v${raw}"

[c]
commands = [
  [ "cc", "--version" ],
  [ "gcc", "--version" ],
  [ "clang", "--version" ]
]
detect_extensions = [ "c", "h" ]
disabled = false
format = "[via](dimmed) [$symbol($version(-$name) )]($style)"
style = "149 bold"
symbol = "C "
version_format = "v${raw}"

[character]
disabled = false
error_symbol = "[â†’](bold red)"
format = "$symbol "
success_symbol = "[â†’](bold green)"
vimcmd_replace_one_symbol = "[â†](bold purple)"
vimcmd_replace_symbol = "[â†](bold purple)"
vimcmd_symbol = "[â†](bold green)"
vimcmd_visual_symbol = "[â†](bold yellow)"

[cmake]
detect_files = [ "CMakeLists.txt", "CMakeCache.txt" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "bold blue"
symbol = "â–³ "
version_format = "v${raw}"

[cmd_duration]
disabled = false
format = "[took](dimmed) [$duration]($style) "
min_time = 2_000
min_time_to_notify = 45_000
show_milliseconds = false
show_notifications = false
style = "yellow bold"

[cobol]
detect_extensions = [ "cbl", "cob", "CBL", "COB" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "bold blue"
symbol = "âš™ï¸ "
version_format = "v${raw}"

[conda]
disabled = false
format = "[via](dimmed) [$symbol$environment]($style) "
ignore_base = true
style = "green bold"
symbol = "ğŸ…’ "
truncation_length = 1

[container]
disabled = false
format = "[$symbol \\[$name\\]]($style) "
style = "red bold dimmed"
symbol = "â¬¢"

[crystal]
detect_extensions = [ "cr" ]
detect_files = [ "shard.yml" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "bold red"
symbol = "ğŸ”® "
version_format = "v${raw}"

[daml]
detect_files = [ "daml.yaml" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "bold cyan"
symbol = "Î› "
version_format = "v${raw}"

[dart]
detect_extensions = [ "dart" ]
detect_files = [ "pubspec.yaml", "pubspec.yml", "pubspec.lock" ]
detect_folders = [ ".dart_tool" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "bold blue"
symbol = "ğŸ¯ "
version_format = "v${raw}"

[deno]
detect_files = [
  "deno.json",
  "deno.jsonc",
  "mod.ts",
  "deps.ts",
  "mod.js",
  "deps.js"
]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "green bold"
symbol = "ğŸ¦• "
version_format = "v${raw}"

[directory]
disabled = false
fish_style_pwd_dir_length = 0
format = "[in](dimmed) [$path]($style)[$read_only]($read_only_style) "
home_symbol = "ğŸ "
read_only = "ğŸ”’"
read_only_style = "red"
repo_root_format = "[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
style = "cyan bold"
truncate_to_repo = true
truncation_length = 3
truncation_symbol = ""
use_logical_path = true
use_os_path_sep = true

[docker_context]
detect_files = [ "docker-compose.yml", "docker-compose.yaml", "Dockerfile" ]
disabled = false
format = "[via](dimmed) [$symbol$context]($style) "
only_with_files = true
style = "blue bold"
symbol = "ğŸ³ "

[dotnet]
detect_extensions = [ "csproj", "fsproj", "xproj" ]
detect_files = [
  "global.json",
  "project.json",
  "Directory.Build.props",
  "Directory.Build.targets",
  "Packages.props"
]
disabled = false
format = "[via](dimmed) [$symbol($version)(ğŸ¯ $tfm )]($style)"
heuristic = true
style = "blue bold"
symbol = ".NET "
version_format = "v${raw}"

[elixir]
detect_files = [ "mix.exs" ]
disabled = false
format = "[via](dimmed) [$symbol($version \\(OTP $otp_version\\) )]($style)"
style = "bold purple"
symbol = "ğŸ’§ "
version_format = "v${raw}"

[elm]
detect_extensions = [ "elm" ]
detect_files = [ "elm.json", "elm-package.json", ".elm-version" ]
detect_folders = [ "elm-stuff" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "cyan bold"
symbol = "ğŸŒ³ "
version_format = "v${raw}"

[erlang]
detect_files = [ "rebar.config", "erlang.mk" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "bold red"
symbol = "î± "
version_format = "v${raw}"

[fennel]
detect_extensions = [ "fnl" ]
disabled = true
format = "[via](dimmed) [$symbol($version)]($style)"
style = "bold green"
symbol = "ğŸ§… "
version_format = "v${raw}"

[fill]
disabled = false
style = "bold black"
symbol = "."

[fossil_branch]
disabled = true
format = "[on](dimmed) [$symbol$branch]($style) "
style = "bold purple"
symbol = "î‚  "
truncation_length = 4_294_967_295
truncation_symbol = "â€¦"

[gcloud]
disabled = false
format = "[on](dimmed) [$symbol$account(@$domain)(\\($region\\))]($style) "
style = "bold blue"
symbol = "â˜ï¸  "

[git_branch]
always_show_remote = false
disabled = false
format = "[on](dimmed) [$symbol$branch(:$remote_branch)]($style) "
only_attached = false
style = "bold purple"
symbol = "î‚  "
truncation_length = 4_294_967_295
truncation_symbol = "â€¦"

[git_commit]
commit_hash_length = 7
disabled = false
format = "[\\($hash$tag\\)]($style) "
only_detached = true
style = "green bold"
tag_disabled = true
tag_max_candidates = 0
tag_symbol = " ğŸ·  "

[git_metrics]
added_style = "bold green"
deleted_style = "bold red"
disabled = true
format = "([+$added]($added_style) )([-$deleted]($deleted_style) )"
only_nonzero_diffs = true

[git_state]
am = "AM"
am_or_rebase = "AM/REBASE"
bisect = "BISECTING"
cherry_pick = "CHERRY-PICKING"
disabled = false
format = "\\([$state( $progress_current/$progress_total)]($style)\\) "
merge = "MERGING"
rebase = "REBASING"
revert = "REVERTING"
style = "bold yellow"

[git_status]
ahead = "â‡¡"
behind = "â‡£"
conflicted = "="
deleted = "âœ˜"
disabled = false
diverged = "â‡•"
format = "([\\[$all_status$ahead_behind\\]]($style) )"
ignore_submodules = false
modified = "!"
renamed = "Â»"
staged = "+"
stashed = "\\$"
style = "red bold"
untracked = "?"
up_to_date = ""

[golang]
detect_extensions = [ "go" ]
detect_files = [
  "go.mod",
  "go.sum",
  "go.work",
  "glide.yaml",
  "Gopkg.yml",
  "Gopkg.lock",
  ".go-version"
]
detect_folders = [ "Godeps" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "bold cyan"
symbol = "ğŸ¹ "
version_format = "v${raw}"

[gradle]
detect_extensions = [ "gradle", "gradle.kts" ]
detect_folders = [ "gradle" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
recursive = false
style = "bold bright-cyan"
symbol = "ğŸ…¶ "
version_format = "v${raw}"

[guix_shell]
disabled = false
format = "[via](dimmed) [$symbol]($style) "
style = "yellow bold"
symbol = "ğŸƒ "

[haskell]
detect_extensions = [ "hs", "cabal", "hs-boot" ]
detect_files = [ "stack.yaml", "cabal.project" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "bold purple"
symbol = "Î» "
version_format = "v${raw}"

[haxe]
detect_extensions = [ "hx", "hxml" ]
detect_files = [ "haxelib.json", "hxformat.json", ".haxerc" ]
detect_folders = [ ".haxelib", "haxe_libraries" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "bold fg:202"
symbol = "âŒ˜ "
version_format = "v${raw}"

[helm]
detect_files = [ "helmfile.yaml", "Chart.yaml" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "bold white"
symbol = "âˆ "
version_format = "v${raw}"

[hg_branch]
disabled = true
format = "[on](dimmed) [$symbol$branch(:$topic)]($style) "
style = "bold purple"
symbol = "î‚  "
truncation_length = 10
truncation_symbol = "â€¦"

[hostname]
disabled = false
format = "[$ssh_symbol$hostname]($style) [in](dimmed) "
ssh_only = true
ssh_symbol = "ğŸŒ "
style = "green bold"
trim_at = "."

[java]
detect_extensions = [ "java", "class", "jar", "gradle", "clj", "cljc" ]
detect_files = [
  "pom.xml",
  "build.gradle.kts",
  "build.sbt",
  ".java-version",
  "deps.edn",
  "project.clj",
  "build.boot",
  ".sdkmanrc"
]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "red dimmed"
symbol = "â˜• "
version_format = "v${raw}"

[jobs]
disabled = false
format = "[$symbol$number]($style) "
number_threshold = 2
style = "bold blue"
symbol = "âœ¦"
symbol_threshold = 1
threshold = 1

[julia]
detect_extensions = [ "jl" ]
detect_files = [ "Project.toml", "Manifest.toml" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "bold purple"
symbol = "à®ƒ "
version_format = "v${raw}"

[kotlin]
detect_extensions = [ "kt", "kts" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
kotlin_binary = "kotlin"
style = "bold blue"
symbol = "ğŸ…º "
version_format = "v${raw}"

[kubernetes]
disabled = true
format = "[$symbol$context( \\($namespace\\))]($style) [in](dimmed) "
style = "cyan bold"
symbol = "â˜¸ "

[line_break]
disabled = false

[localip]
disabled = true
format = "[$localipv4]($style) "
ssh_only = true
style = "yellow bold"

[lua]
detect_extensions = [ "lua" ]
detect_files = [ ".lua-version" ]
detect_folders = [ "lua" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
lua_binary = "lua"
style = "bold blue"
symbol = "ğŸŒ™ "
version_format = "v${raw}"

[memory_usage]
disabled = true
format = "[via](dimmed) $symbol[$ram( | $swap)]($style) "
style = "white bold dimmed"
symbol = "ğŸ "
threshold = 75

[meson]
disabled = false
format = "[via](dimmed) [$symbol$project]($style) "
style = "blue bold"
symbol = "â¬¢ "
truncation_length = 4_294_967_295
truncation_symbol = "â€¦"

[nim]
detect_extensions = [ "nim", "nims", "nimble" ]
detect_files = [ "nim.cfg" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "yellow bold"
symbol = "ğŸ‘‘ "
version_format = "v${raw}"

[nix_shell]
disabled = false
format = "[via](dimmed) [$symbol$state( \\($name\\))]($style) "
heuristic = false
impure_msg = "impure"
pure_msg = "pure"
style = "bold blue"
symbol = "â„ï¸  "
unknown_msg = ""

[nodejs]
detect_extensions = [ "js", "mjs", "cjs", "ts", "mts", "cts" ]
detect_files = [ "package.json", ".node-version", ".nvmrc" ]
detect_folders = [ "node_modules" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
not_capable_style = "bold red"
style = "bold green"
symbol = "îœ˜ "
version_format = "v${raw}"

[ocaml]
detect_extensions = [ "opam", "ml", "mli", "re", "rei" ]
detect_files = [ "dune", "dune-project", "jbuild", "jbuild-ignore", ".merlin" ]
detect_folders = [ "_opam", "esy.lock" ]
disabled = false
format = "[via](dimmed) [$symbol($version)(\\($switch_indicator$switch_name\\) )]($style)"
global_switch_indicator = ""
local_switch_indicator = "*"
style = "bold yellow"
symbol = "ğŸ« "
version_format = "v${raw}"

[opa]
detect_extensions = [ "rego" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "bold blue"
symbol = "ğŸª–  "
version_format = "v${raw}"

[openstack]
disabled = false
format = "[on](dimmed) [$symbol$cloud(\\($project\\))]($style) "
style = "bold yellow"
symbol = "â˜ï¸  "

[os]
disabled = true
format = "[$symbol]($style)"
style = "bold white"

  [os.symbols]
  Alpaquita = "ğŸ”” "
  Alpine = "ğŸ”ï¸ "
  Amazon = "ğŸ™‚ "
  Android = "ğŸ¤– "
  Arch = "ğŸ—ï¸ "
  Artix = "ğŸ—ï¸ "
  CentOS = "ğŸ’  "
  Debian = "ğŸŒ€ "
  DragonFly = "ğŸ‰ "
  Emscripten = "ğŸ”— "
  EndeavourOS = "ğŸš€ "
  Fedora = "ğŸ© "
  FreeBSD = "ğŸ˜ˆ "
  Garuda = "ğŸ¦… "
  Gentoo = "ğŸ—œï¸ "
  HardenedBSD = "ğŸ›¡ï¸ "
  Illumos = "ğŸ¦ "
  Linux = "ğŸ§ "
  Mabox = "ğŸ“¦ "
  Macos = "ğŸ "
  Manjaro = "ğŸ¥­ "
  Mariner = "ğŸŒŠ "
  MidnightBSD = "ğŸŒ˜ "
  Mint = "ğŸŒ¿ "
  NetBSD = "ğŸš© "
  NixOS = "â„ï¸ "
  OpenBSD = "ğŸ¡ "
  OpenCloudOS = "â˜ï¸ "
  OracleLinux = "ğŸ¦´ "
  Pop = "ğŸ­ "
  Raspbian = "ğŸ“ "
  RedHatEnterprise = "ğŸ© "
  Redhat = "ğŸ© "
  Redox = "ğŸ§ª "
  SUSE = "ğŸ¦ "
  Solus = "â›µ "
  Ubuntu = "ğŸ¯ "
  Unknown = "â“ "
  Windows = "ğŸªŸ "
  openEuler = "ğŸ¦‰ "
  openSUSE = "ğŸ¦ "

[package]
disabled = false
display_private = false
format = "[is](dimmed) [$symbol$version]($style) "
style = "208 bold"
symbol = "ğŸ“¦ "
version_format = "v${raw}"

[perl]
detect_extensions = [ "pl", "pm", "pod" ]
detect_files = [
  "Makefile.PL",
  "Build.PL",
  "cpanfile",
  "cpanfile.snapshot",
  "META.json",
  "META.yml",
  ".perl-version"
]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "149 bold"
symbol = "ğŸª "
version_format = "v${raw}"

[php]
detect_extensions = [ "php" ]
detect_files = [ "composer.json", ".php-version" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "147 bold"
symbol = "ğŸ˜ "
version_format = "v${raw}"

[pijul_channel]
disabled = true
format = "[on](dimmed) [$symbol$channel]($style) "
style = "bold purple"
symbol = "î‚  "
truncation_length = 4_294_967_295
truncation_symbol = "â€¦"

[pulumi]
disabled = false
format = "[via](dimmed) [$symbol($username@)$stack]($style) "
search_upwards = true
style = "bold 5"
symbol = "ï†² "
version_format = "v${raw}"

[purescript]
detect_extensions = [ "purs" ]
detect_files = [ "spago.dhall" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "bold white"
symbol = "<=> "
version_format = "v${raw}"

[python]
detect_extensions = [ "py" ]
detect_files = [
  "requirements.txt",
  ".python-version",
  "pyproject.toml",
  "Pipfile",
  "tox.ini",
  "setup.py",
  "__init__.py"
]
disabled = false
format = "[via](dimmed) [${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"
pyenv_prefix = "pyenv "
pyenv_version_name = false
python_binary = [ "python", "python3", "python2" ]
style = "yellow bold"
symbol = "ğŸ "
version_format = "v${raw}"

[raku]
detect_extensions = [ "p6", "pm6", "pod6", "raku", "rakumod" ]
detect_files = [ "META6.json" ]
disabled = false
format = "[via](dimmed) [$symbol($version-$vm_version)]($style)"
style = "149 bold"
symbol = "ğŸ¦‹ "
version_format = "${raw}"

[red]
detect_extensions = [ "red", "reds" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "red bold"
symbol = "ğŸ”º "
version_format = "v${raw}"

[rlang]
detect_extensions = [ "R", "Rd", "Rmd", "Rproj", "Rsx" ]
detect_files = [ ".Rprofile" ]
detect_folders = [ ".Rproj.user" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "blue bold"
symbol = "ğŸ“ "
version_format = "v${raw}"

[ruby]
detect_extensions = [ "rb" ]
detect_files = [ "Gemfile", ".ruby-version" ]
detect_variables = [ "RUBY_VERSION", "RBENV_VERSION" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "bold red"
symbol = "ğŸ’ "
version_format = "v${raw}"

[rust]
detect_extensions = [ "rs" ]
detect_files = [ "Cargo.toml" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "bold red"
symbol = "ğŸ¦€ "
version_format = "v${raw}"

[scala]
detect_extensions = [ "sbt", "scala" ]
detect_files = [ ".scalaenv", ".sbtenv", "build.sbt" ]
detect_folders = [ ".metals" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "red bold"
symbol = "ğŸ†‚ "
version_format = "v${raw}"

[shell]
bash_indicator = "bsh"
cmd_indicator = "cmd"
disabled = true
elvish_indicator = "esh"
fish_indicator = "fsh"
format = "[$indicator]($style) "
ion_indicator = "ion"
nu_indicator = "nu"
powershell_indicator = "psh"
style = "white bold"
tcsh_indicator = "tsh"
unknown_indicator = ""
xonsh_indicator = "xsh"
zsh_indicator = "zsh"

[shlvl]
disabled = true
format = "[$symbol$shlvl]($style) "
repeat = false
style = "bold yellow"
symbol = "â†•ï¸  "
threshold = 2

[singularity]
disabled = false
format = "[$symbol\\[$env\\]]($style) "
style = "blue bold dimmed"
symbol = ""

[spack]
disabled = false
format = "[via](dimmed) [$symbol$environment]($style) "
style = "blue bold"
symbol = "ğŸ…¢ "
truncation_length = 1

[status]
disabled = true
format = "[$symbol$status]($style) "
map_symbol = false
not_executable_symbol = "ğŸš«"
not_found_symbol = "ğŸ”"
pipestatus = false
pipestatus_format = "\\[$pipestatus\\] => [$symbol$common_meaning$signal_name$maybe_int]($style)"
pipestatus_separator = "|"
recognize_signal_code = true
sigint_symbol = "ğŸ§±"
signal_symbol = "âš¡"
style = "bold red"
success_symbol = ""
symbol = "âŒ"

[sudo]
allow_windows = false
disabled = true
format = "[as $symbol]($style)"
style = "bold blue"
symbol = "ğŸ§™ "

[swift]
detect_extensions = [ "swift" ]
detect_files = [ "Package.swift" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "bold 202"
symbol = "ğŸ¦ "
version_format = "v${raw}"

[terraform]
detect_extensions = [ "tf", "tfplan", "tfstate" ]
detect_folders = [ ".terraform" ]
disabled = false
format = "[via](dimmed) [$symbol$workspace]($style) "
style = "bold 105"
symbol = "ğŸ’  "
version_format = "v${raw}"

[time]
disabled = true
format = "[at](dimmed) [$time]($style) "
style = "bold yellow"
time_range = "-"
use_12hr = false
utc_time_offset = "local"

[username]
disabled = false
format = '[$user]($style) '
show_always = true
style_root = "red bold"
style_user = "yellow bold"

[vagrant]
detect_files = [ "Vagrantfile" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "cyan bold"
symbol = "â± "
version_format = "v${raw}"

[vcsh]
disabled = false
format = "vcsh [$symbol$repo]($style) "
style = "bold yellow"
symbol = ""

[vlang]
detect_extensions = [ "v" ]
detect_files = [ "v.mod", "vpkg.json", ".vpkg-lock.json" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "blue bold"
symbol = "V "
version_format = "v${raw}"

[zig]
detect_extensions = [ "zig" ]
disabled = false
format = "[via](dimmed) [$symbol($version)]($style)"
style = "bold yellow"
symbol = "â†¯ "
version_format = "v${raw}"